

Monotonicity ($m-1$ inequalities)



\begin{align}
	\Xi^{(1)}(x,y,s_y) =&
	\sum_{ (u_1 u_2) \in U_2}
	(\lambda_0x_{u_1} x_{u_2 +1 } +3\lambda_0y_{t(u_1 u_2)} -2\lambda_0x_{u_1} y_{t(u_1 u_2)} -2\lambda_0x_{u_2 +1 } y_{t(u_1 u_2)})  
	\nonumber\\&
	+  
	\sum_{(u_1 u_2 u_3 u_4)  \in U_4} \lambda y_{t(u_2 u_1)} y_{t(u_4 u_3)}
	+\sum_{(u_1 u_2 u_3 u_4)  \in U_4} \lambda y_{t(u_1 u_2)} y_{t(u_3 u_4)}\nonumber\\&
	+\sum_{(v_1 v_2) \in V_2} 2^{l(v_1)+l(v_2)}\lambda s_{yv_1}s_{y v_2}
	+\sum_{(u_1 u_2 u_3 u_4)  \in U_4} (-2)\lambda y_{t(u_2 u_1)} y_{t(u_3 u_4)}\nonumber\\&
	+\sum_{(u_1 u_2 v) \in H }2^{l(v)+1}\lambda y_{t(u_2 u_1)}s_{y v}
	+\sum_{(u_1 u_2 v) \in H }(-1) 2^{l(v)+1} \lambda y_{t(u_1 u_2)}s_{y v}   
\end{align}

\begin{align}
	x \in \mathbb{B}^{nm},\quad
	y \in \mathbb{B}^{2(m-1)(n-d)d} ,\quad
	s_y \in \mathbb{B}  {}^{\wedge} \{ (m-1) \left \lfloor 1+ \log_2 [(n-d)d] \right \rfloor \}  .
\end{align}

In [1]:
import numpy as np
import math
import sys
import random

n=6; m=3;# d_vec = [0,0,1,0,0]

d_modul = 2
def random_no_prob(n,d_modul):
  d = [0] * n
  indices_to_set_to_one = random.sample(range(n), d_modul)
  for index in indices_to_set_to_one:
      d[index] = 1
  return d
d_vec = random_no_prob(n,d_modul)

d = sum(d_vec)
if d_vec == 0 or d_vec == n:
	sys.exit(0)

param = (n-d)*d
N_y = math.floor(1+math.log2(param))
dim_x = n*m
dim_y = 2*(m-1)*param
dim_sy = (m-1)*N_y
offset_y = dim_x
offset_sy = dim_x + dim_y
##############  x   #        y      #   s_y
##############  nm  #  2(m-1)(n-d)d #  (m-1)N_y
# n=5; m=3; ##  15  #        24     #     6
dim_qubo   =    n*m  +    dim_y     +    dim_sy

Q = np.zeros([dim_qubo,dim_qubo])
c = 0

lambda0 = 100
lambda1 = 50 # it has the meaning of lambda
lambda2 = 300 # for BSM

print("number of counterparts: ",n)
print("number of classes: ",m)
print("vector of default: ",d_vec)
print("number of defaults: ",d)
print("dimension of the problem: ", dim_qubo)
print("lambda coefficients:")
print(lambda0, lambda1, lambda2, sep=', ')

number of counterparts:  6
number of classes:  3
vector of default:  [0, 1, 0, 0, 0, 1]
number of defaults:  2
dimension of the problem:  58
lambda coefficients:
100, 50, 300


\begin{align}
    C^{\pm} &= \{(i_1  i_2) \in \{1, 2, \dots, n\}^2 \mid d_{i_1 i_2} = \pm 1\}, \\
    C &= C^+ \cup C^-
\end{align}

In [2]:
C_set_minus = []
C_set = []
for i1 in range(n):
	for i2 in range(n):
		if d_vec[i1]-d_vec[i2] == -1:
			C_set_minus.append([i1+1,i2+1])
		if d_vec[i1]-d_vec[i2] != 0:
			C_set.append([i1+1,i2+1])
print(C_set_minus)
print(C_set)

[[1, 2], [1, 6], [3, 2], [3, 6], [4, 2], [4, 6], [5, 2], [5, 6]]
[[1, 2], [1, 6], [2, 1], [2, 3], [2, 4], [2, 5], [3, 2], [3, 6], [4, 2], [4, 6], [5, 2], [5, 6], [6, 1], [6, 3], [6, 4], [6, 5]]


\begin{align}
    U_2 &= \{(u_1  u_2)\in \{0, 1, \dots, nm - 1\}^2 \mid u_r = (i_r-1)m+j-1,\ \text{for every}\ r\in\{1,2\},\ (i_1  i_2  j)\in Q_3\}
\end{align}

In [3]:
u2 = []
for j in range(m-1):
	for item_c_set in C_set:
		u2_1 = (item_c_set[0] -1)*m + (j+1) -1
		u2_2 = (item_c_set[1] -1)*m + (j+1) -1
		u2.append([u2_1 , u2_2])
print(u2)

[[0, 3], [0, 15], [3, 0], [3, 6], [3, 9], [3, 12], [6, 3], [6, 15], [9, 3], [9, 15], [12, 3], [12, 15], [15, 0], [15, 6], [15, 9], [15, 12], [1, 4], [1, 16], [4, 1], [4, 7], [4, 10], [4, 13], [7, 4], [7, 16], [10, 4], [10, 16], [13, 4], [13, 16], [16, 1], [16, 7], [16, 10], [16, 13]]


\begin{align}
    Q_3 &= \{ (i_1  i_2 j) \in \{1, 2, \dots, n\}^2 \times \{1, 2, \dots, m-1\} \mid (i_1  i_2) \in C\}
\end{align}

In [4]:
print(u2)

[[0, 3], [0, 15], [3, 0], [3, 6], [3, 9], [3, 12], [6, 3], [6, 15], [9, 3], [9, 15], [12, 3], [12, 15], [15, 0], [15, 6], [15, 9], [15, 12], [1, 4], [1, 16], [4, 1], [4, 7], [4, 10], [4, 13], [7, 4], [7, 16], [10, 4], [10, 16], [13, 4], [13, 16], [16, 1], [16, 7], [16, 10], [16, 13]]


\begin{align}
	U_4 = \{ (u_1 u_2 u_3 u_4) \in \mathbb{N}[0,nm-1]^4|&u_r = (i_r-1)m+j-1, \text{for every}\nonumber\\&r\in\{1,2,3,4\}, (i_1 i_2)\in C^-, (i_3 i_4)\in C^-\}
\end{align}

In [5]:
u4 = []
for j in range(m - 1):
    for item_c_set_minus_1 in C_set_minus:
        u_1 = (item_c_set_minus_1[0] - 1) * m + (j + 1) - 1
        u_2 = (item_c_set_minus_1[1] - 1) * m + (j + 1) - 1
        for item_c_set_minus_2 in C_set_minus:
            u_3 = (item_c_set_minus_2[0] - 1) * m + (j + 1) - 1
            u_4 = (item_c_set_minus_2[1] - 1) * m + (j + 1) - 1
            u4.append([u_1, u_2, u_3, u_4])

$$
	V_2 =\{ (v_1   v_2) \in \mathbb{N}[0,N_y \cdot(m-1)-1] ^2|v_r = l_r \cdot (m-1)+j-1 \ \text{for every}\
	l_r \in \mathbb{N}[0, N_y -1]   ,  r\in\{1,2\}    \},
$$

In [6]:
l2j1 = []
for l1 in range(N_y):
	for l2 in range(N_y):
		for j in range(m-1):
			l2j1.append([l1,l2,j+1])
v2 = []
for l2j1_item in l2j1:
	v_1 = l2j1_item[0]*(m-1) + l2j1_item[2] -1
	v_2 = l2j1_item[1]*(m-1) + l2j1_item[2] -1
	v2.append([v_1,v_2])

\begin{align}
	H = \{(u_1 u_2 v)  \in  \mathbb{N}[0,nm-1]^2 \times \mathbb{N}[0,N_y \cdot (m-1)-1]
	|& u_r = (i_r-1)m+j-1,\nonumber\\&v=l\cdot (m-1)+j-1 \nonumber\\& \text{for every}\ r \in \{1,2\}, \ (i_1 i_2)\in C^- \}
\end{align}

In [7]:
h = []
for j in range(m-1):
	for c_min_item in C_set_minus:
		u_1=(c_min_item[0]-1)*m + (j+1) -1
		u_2=(c_min_item[1]-1)*m + (j+1) -1
		for l in range(N_y):
			v = l*(m-1) + (j+1) -1
			h.append([u_1,u_2,v])

\begin{align}
	l(v) = \left \lfloor v/(m-1) \right\rfloor
\end{align}

In [8]:
def l_func(v):
	return math.floor(v/(m-1))

\begin{align}
	\sum_{ (u_1 u_2) \in U_2}
	(\lambda_0x_{u_1} x_{u_2 +1 } +3\lambda_0y_{t(u_1 u_2)} -2\lambda_0x_{u_1} y_{t(u_1 u_2)} -2\lambda_0x_{u_2 +1 } y_{t(u_1 u_2)})  
\end{align}

In [9]:
print(u2)

[[0, 3], [0, 15], [3, 0], [3, 6], [3, 9], [3, 12], [6, 3], [6, 15], [9, 3], [9, 15], [12, 3], [12, 15], [15, 0], [15, 6], [15, 9], [15, 12], [1, 4], [1, 16], [4, 1], [4, 7], [4, 10], [4, 13], [7, 4], [7, 16], [10, 4], [10, 16], [13, 4], [13, 16], [16, 1], [16, 7], [16, 10], [16, 13]]


In [10]:
for u2_item in u2:
	u_1 = u2_item[0]; u_2 = u2_item[1]
	if u_1==u_2+1:
		Q[u_1,u_2+1] += lambda0
	else:
		Q[u_1,u_2+1] += lambda0*0.5
		Q[u_2+1,u_1] += lambda0*0.5

for u2_item in u2:
	u_1 = u2_item[0]; u_2 = u2_item[1]
	t=u2.index([u_1,u_2])
	Q[ offset_y + t, offset_y + t ] += lambda0*3

for u2_item in u2:
	u_1 = u2_item[0]; u_2 = u2_item[1]
	t=u2.index([u_1,u_2])
	Q[u_1,offset_y + t] += lambda0*(-2)*0.5
	Q[offset_y + t,u_1] += lambda0*(-2)*0.5

for u2_item in u2:
	u_1 = u2_item[0]; u_2 = u2_item[1]
	t=u2.index([u_1,u_2])
	Q[u_2+1,offset_y + t] += lambda0*(-2)*0.5
	Q[offset_y + t,u_2+1] += lambda0*(-2)*0.5

\begin{align}
	\sum_{(u_1 u_2 u_3 u_4)  \in U_4} \lambda y_{t(u_2 u_1)} y_{t(u_4 u_3)}
	+\sum_{(u_1 u_2 u_3 u_4)  \in U_4} \lambda y_{t(u_1 u_2)} y_{t(u_3 u_4)}
\end{align}

In [11]:
# first summation
for u4_item in u4:
	u_1 = u4_item[0]; u_2 = u4_item[1]
	u_3 = u4_item[2]; u_4 = u4_item[3]
	t21 = u2.index([u_2,u_1])
	t43 = u2.index([u_4,u_3])
	if t21==t43:
		Q[ offset_y + t21 , offset_y + t43 ] += lambda1
	else:
		Q[ offset_y + t21 , offset_y + t43 ] += lambda1*0.5
		Q[ offset_y + t43 , offset_y + t21 ] += lambda1*0.5
# second summation
for u4_item in u4:
	u_1 = u4_item[0]; u_2 = u4_item[1]
	u_3 = u4_item[2]; u_4 = u4_item[3]
	t12 = u2.index([u_1,u_2])
	t34 = u2.index([u_3,u_4])
	if t12==t34:
		Q[ offset_y + t12 , offset_y + t34 ] += lambda1
	else:
		Q[ offset_y + t12 , offset_y + t34 ] += lambda1*0.5
		Q[ offset_y + t34 , offset_y + t12 ] += lambda1*0.5

\begin{align}
	+\sum_{(v_1 v_2) \in V_2} 2^{l(v_1)+l(v_2)}\lambda s_{yv_1}s_{y v_2}
	+\sum_{(u_1 u_2 u_3 u_4)  \in U_4} (-2)\lambda y_{t(u_2 u_1)} y_{t(u_3 u_4)}
\end{align}

In [12]:
# first summation
for v2_item in v2:	
	v_1 = v2_item[0]; v_2 = v2_item[1]
	if v_1==v_2:
		Q[ offset_sy + v_1 , offset_sy + v_2 ] += math.pow( 2, l_func(v_1) + l_func(v_2) )*lambda1
	else:
		Q[ offset_sy + v_1 , offset_sy + v_2 ] += math.pow( 2, l_func(v_1) + l_func(v_2) )*lambda1*0.5
		Q[ offset_sy + v_2 , offset_sy + v_1 ] += math.pow( 2, l_func(v_1) + l_func(v_2) )*lambda1*0.5
# second summation
for u4_item in u4:
	u_1 = u4_item[0]; u_2 = u4_item[1]
	u_3 = u4_item[2]; u_4 = u4_item[3]
	t21 = u2.index([u_2,u_1])
	t34 = u2.index([u_3,u_4])
	if t21==t34:
		Q[ offset_y + t21 , offset_y + t34 ] += lambda1*(-2)
	else:
		Q[ offset_y + t21 , offset_y + t34 ] += lambda1*(-2)*0.5
		Q[ offset_y + t34 , offset_y + t21 ] += lambda1*(-2)*0.5

\begin{align}
	\sum_{(u_1 u_2 v) \in H }2^{l(v)+1}\lambda y_{t(u_2 u_1)}s_{y v}
	+\sum_{(u_1 u_2 v) \in H }(-1) 2^{l(v)+1} \lambda y_{t(u_1 u_2)}s_{y v}   
\end{align}

In [13]:
# first summation
for h_item in h:
	u_1 = h_item[0]; u_2 = h_item[1]; v = h_item[2]
	t21 = u2.index([u_2,u_1])
	Q[ offset_y + t21 , offset_sy + v ] += math.pow( 2, l_func(v) + 1 )*lambda1*0.5
	Q[ offset_sy + v , offset_y + t21 ] += math.pow( 2, l_func(v) + 1 )*lambda1*0.5
# second summation
for h_item in h:
	u_1 = h_item[0]; u_2 = h_item[1]; v = h_item[2]
	t12 = u2.index([u_1,u_2])
	Q[ offset_y + t12 , offset_sy + v ] += (-1)*math.pow( 2, l_func(v) + 1 )*lambda1*0.5
	Q[ offset_sy + v , offset_y + t12 ] += (-1)*math.pow( 2, l_func(v) + 1 )*lambda1*0.5

Binary staircase matrix

In [14]:
QQ = np.zeros([n*m,n*m])
cc=0
# penalty: "one counterpart per class"
for ii in range(n):
    for jj in range(m):
        tt = ii*m+jj
        QQ[tt][tt] += -1
    for jj in range(m-1):
        for kk in range(jj+1,m):
            tt = ii*m+jj
            rr = ii*m+kk
            QQ[tt][rr] += 1
            QQ[rr][tt] += 1
    cc += 1
# penalty: "first counterpart in first class"
for jj in range(1, m):
    QQ[jj][jj] += 1
    QQ[0][jj] -= 0.5
    QQ[jj][0] -= 0.5

# penalty: "last counterpart in the last class"
for jj in range(m-1):
    tt = (n-1)*m+jj
    QQ[tt][tt] += 1
    QQ[(n*m)-1][tt] -= 0.5
    QQ[tt][(n*m)-1] -= 0.5

# penalty: "penalize not permitted submatrix"
# a submatrix is
# [[x1, x1], [x3, x4]]
for ii in range(n-1):
    for jj in range(m-1):
        x1 = ii*m+jj
        x2 = x1+1
        x3 = (ii+1)*m+jj
        x4 = x3+1
        # add linear terms
        QQ[x1][x1] += 1
        QQ[x4][x4] += 1
        # add quadratic terms
        QQ[x1][x2] += 0.5
        QQ[x2][x1] += 0.5
        QQ[x1][x3] -= 0.5
        QQ[x3][x1] -= 0.5
        QQ[x1][x4] -= 1
        QQ[x4][x1] -= 1
        QQ[x2][x3] += 0.5
        QQ[x3][x2] += 0.5
        QQ[x2][x4] -= 0.5
        QQ[x4][x2] -= 0.5
        QQ[x3][x4] += 0.5
        QQ[x4][x3] += 0.5

# penalty: "penalize restarting from class 0"
for ii in range(n-1):
    x1 = ii*m
    x2 = x1+1
    x3 = (ii+1)*m
    QQ[x3][x3] += 1
    QQ[x1][x3] -= 0.5
    QQ[x3][x1] -= 0.5
    QQ[x2][x3] -= 0.5
    QQ[x3][x2] -= 0.5
    QQ[x1][x2] += 0.5
    QQ[x2][x1] += 0.5

Adding BSM to monotonicity

In [15]:
c=c+cc*lambda2
QQ = QQ*lambda2
QQ=np.pad(QQ, ((0, dim_qubo-n*m), (0, dim_qubo-n*m)), mode='constant', constant_values=0)
Q = QQ+Q
#dim_qubo=n*m

Finding a solution

In [16]:
import gurobipy as gp
from gurobipy import GRB


# Create a new model
mm = gp.Model("qubo_solver")

# Create binary variables
x = mm.addVars(dim_qubo, vtype=GRB.BINARY, name="x")

# Set the objective function: minimize x' * Q * x + c
obj = gp.quicksum(Q[i][j] * x[i] * x[j] for i in range(dim_qubo) for j in range(dim_qubo)) + c
mm.setObjective(obj, GRB.MINIMIZE)

# Solve the model
mm.optimize()

# Print the solution
if mm.status == GRB.OPTIMAL:
    print("Optimal solution found.")
    solution = [int(v.X) for v in x.values()]
    print(f"Optimal variable values (x): {solution}")
    print(f"Optimal objective value: {mm.ObjVal}")
else:
    print("No optimal solution found.")

Set parameter Username
Set parameter LicenseID to value 2685653
Gurobi Optimizer version 12.0.3 build v12.0.3rc0 (linux64 - "Ubuntu 24.04.3 LTS")

CPU model: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads

Optimize a model with 0 rows, 58 columns and 0 nonzeros
Model fingerprint: 0x9ebd47d7
Model has 566 quadratic objective terms
Variable types: 0 continuous, 58 integer (58 binary)
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  QObjective range [1e+02, 6e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [0e+00, 0e+00]
Found heuristic solution: objective 1800.0000000
Found heuristic solution: objective 50.0000000
Presolve time: 0.00s
Presolved: 0 rows, 58 columns, 0 nonzeros
Presolved model has 573 quadratic objective terms
Variable types: 0 continuous, 58 integer (58 binary)

Root relaxation: objective -6.002867e+03, 

Recap of the problem and solution

In [17]:
print("number of counterparts: ",n)
print("number of classes: ",m)
print("vector of default: ",d_vec)
print("number of defaults: ",d)
print("dimension of the problem: ", dim_qubo)
print("lambda coefficients:")
print(lambda0, lambda1, lambda2, sep=', ')
sol_nm=solution[:n*m]
sol_nm_arr=np.array(sol_nm)
sol_nm_arr_re=sol_nm_arr.reshape(n,m)
print("solution:")
print(sol_nm_arr_re)

number of counterparts:  6
number of classes:  3
vector of default:  [0, 1, 0, 0, 0, 1]
number of defaults:  2
dimension of the problem:  58
lambda coefficients:
100, 50, 300
solution:
[[1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]]
