

Monotonicity ($m-1$ inequalities)



\begin{align}
	\Xi^{(1)}(x,y,s,s_y) =&
	\sum_{ (u_1,u_2) \in U_2}
	\bigg[
	\lambda_1y_{t(u_1, u_2)} \cdot (1-x_{u_1})+\lambda_2 y_{t(u_1, u_2)} \cdot (1-x_{u_2+1}) \nonumber\\&
	+\lambda_3 \cdot
	(1-x_{u_1}-x_{u_2 +1}+3y_{t(u_1, u_2)}-s_{0t(u_1, u_2)} + 2 x_{u_1} x_{u_2 +1}- 2x_{u_1} y_{t(u_1, u_2)}
	\nonumber\\&+ 2 x_{u_1} s_{0 t(u_1, u_2)}
	+4  x_{u_1}  s_{1 t(u_1, u_2)}
	-2 x_{u_2 +1}y_{t(u_1, u_2)}+2x_{u_2 +1} s_{0t(u_1, u_2)}\nonumber\\&+4 x_{u_2 +1}s_{1t(u_1, u_2)}-2 y_{t(u_1, u_2)} s_{0t(u_1, u_2)}-4y_{t(u_1, u_2)}s_{1t(u_1, u_2)}+
	4s_{0t(u_1, u_2)}s_{1t(u_1, u_2)})
	\bigg]\nonumber\\&
	+  
	\sum_{(u_1,u_2,u_3,u_4)  \in U_4} \lambda_4 y_{t(u_2,u_1)} y_{t(u_4,u_3)}
	+\sum_{(u_1,u_2,u_3,u_4)  \in U_4} \lambda_4 y_{t(u_1,u_2)} y_{t(u_3,u_4)}\nonumber\\&
	+\sum_{(v_1,v_2) \in V_2} 2^{l(v_1)+l(v_2)}\lambda_4 s_{yv_1}s_{y v_2}
	+\sum_{(u_1,u_2,u_3,u_4)  \in U_4} (-2)\lambda_4 y_{t(u_2,u_1)} y_{t(u_3,u_4)}\nonumber\\&
	+\sum_{(u_1,u_2,v) \in H }2^{l(v)+1}\lambda_4 y_{t(u_2,u_1)}s_{y v}
	+\sum_{(u_1,u_2,v) \in H }(-1) 2^{l(v)+1} \lambda_4y_{t(u_1,u_2)}s_{y v}   
\end{align}

$x \in \mathbb{B}^{nm}$,
$y \in \mathbb{B}^{2(m-1)(n-d)d}$,
$s_0 \in \mathbb{B}^{2(m-1)(n-d)d}$, $s_1 \in \mathbb{B}^{2(m-1)(n-d)d}$,
$s_y \in \mathbb{B}^{(m-1) N_y }$


In [1]:
import numpy as np
import math
import random
n=5; m=3
d_modul = 2
#d_vec = [0,0,1,0,1,1]
def random_no_prob(n,d_modul):
  d = [0] * n
  indices_to_set_to_one = random.sample(range(n), d_modul)
  for index in indices_to_set_to_one:
      d[index] = 1
  return d
d_vec = random_no_prob(n,d_modul)
#d_vec = [0,0,0,0,1]
print("default vector: ",d_vec)
d = sum(d_vec)
param = (n-d)*d
N_y = math.floor(1+math.log2(param))
dim_y = 2*(m-1)*(n-d)*d #also dim_s_0 and dim_s_1
dim_sy = N_y*(m-1)
offset1 = n*m
offset2 = n*m + dim_y
offset3 = n*m + 2*dim_y
offset4 = n*m + 3*dim_y
##############  x   #        y      #      s_0      #      s_1	   #   s_y
##############  nm  #  2(m-1)(n-d)d #  2(m-1)(n-d)d # 2(m-1)(n-d)d #  (m-1)N_y
# n=5; m=3; ##  15  #        24      #     24		#	    24     #    6
dim_qubo =    n*m    +    dim_y      +    dim_y     +      dim_y    +   dim_sy
#dim_qubo =    n*m
print("number of counterparts: ",n)
print("number of classes: ",m)
print("vector of default values: ",d_vec)
print("num of default: ",d)
print("dimension of the problem: ", dim_qubo)
Q = np.zeros([dim_qubo,dim_qubo])
c = 0

lambda1 = 10
lambda2 = 10
lambda3 = 10
lambda4 = 50
lambda5 = 100 #for the staircase matrix
print("lambda coefficients:")
print(lambda1, lambda2, lambda3, lambda4,lambda5, sep=', ')

default vector:  [0, 0, 1, 1, 0]
number of counterparts:  5
number of classes:  3
vector of default values:  [0, 0, 1, 1, 0]
num of default:  2
dimension of the problem:  93
lambda coefficients:
10, 10, 10, 50, 100


\begin{align}
	C^{-} = \{(i_1,i_2) \in \mathbb{N}[1,n]^2 | d_{i_1 i_2} = -1\}   ,
\end{align}
$$
\begin{align}
	C = \{(i_1,i_2) \in \mathbb{N}[1,n]^2 | d_{i_1 i_2} \in \{-1,+1\} \}
\end{align}
$$

In [2]:
minus_set = [] #list of the couples of indices corresponding to d_{i1 i2} equal to -1
non_zero_set = [] #list of the couples of indices corresponding to d_{i1 i2} different from 0
for i1 in range(n):
	for i2 in range(n):
		if d_vec[i1]-d_vec[i2] == -1:
			minus_set.append([i1+1,i2+1])
		if d_vec[i1]-d_vec[i2] != 0:
			non_zero_set.append([i1+1,i2+1])
print("the list of the couples of indices corresponding to d_{i1 i2} equal to -1")
print(minus_set)
print("the list of the couples of indices corresponding to d_{i1 i2} different from 0 is")
print(non_zero_set)

the list of the couples of indices corresponding to d_{i1 i2} equal to -1
[[1, 3], [1, 4], [2, 3], [2, 4], [5, 3], [5, 4]]
the list of the couples of indices corresponding to d_{i1 i2} different from 0 is
[[1, 3], [1, 4], [2, 3], [2, 4], [3, 1], [3, 2], [3, 5], [4, 1], [4, 2], [4, 5], [5, 3], [5, 4]]


Building the indices sets for the constraint $x_1 x_2 = y$

\begin{align}
	U_2 = \{(u_1,u_2)\in \mathbb{N}[0,nm-2]^2|u_r = (i_r-1)m+j-1,\ \text{for every}\ r\in\{1,2\}, (i_1,i_2)\in C \}
\end{align}

In [3]:
u2 = []
for j in range(m-1):
	for nz_item in non_zero_set:
		u2_1=(nz_item[0]-1)*m + (j+1) -1
		u2_2=(nz_item[1]-1)*m + (j+1) -1
		u2.append([u2_1,u2_2])
print(u2)

[[0, 6], [0, 9], [3, 6], [3, 9], [6, 0], [6, 3], [6, 12], [9, 0], [9, 3], [9, 12], [12, 6], [12, 9], [1, 7], [1, 10], [4, 7], [4, 10], [7, 1], [7, 4], [7, 13], [10, 1], [10, 4], [10, 13], [13, 7], [13, 10]]


\begin{align}
	U_4 = \{ (u_1,u_2,u_3,u_4) \in \mathbb{N}[0,nm-2]^4|&u_r = (i_r-1)m+j-1, \text{for every}\nonumber\\&r\in\{1,2,3,4\}, (i_1,i_2)\in C^-, (i_3,i_4)\in C^-\}
\end{align}

In [4]:
u4 = []
for j in range(m-1):
	for minus_item1 in minus_set:
		for minus_item2 in minus_set:
			u4_1=(minus_item1[0]-1)*m + (j+1) -1
			u4_2=(minus_item1[1]-1)*m + (j+1) -1
			u4_3=(minus_item2[0]-1)*m + (j+1) -1
			u4_4=(minus_item2[1]-1)*m + (j+1) -1
			u4.append([u4_1,u4_2,u4_3,u4_4])
print(u4)

[[0, 6, 0, 6], [0, 6, 0, 9], [0, 6, 3, 6], [0, 6, 3, 9], [0, 6, 12, 6], [0, 6, 12, 9], [0, 9, 0, 6], [0, 9, 0, 9], [0, 9, 3, 6], [0, 9, 3, 9], [0, 9, 12, 6], [0, 9, 12, 9], [3, 6, 0, 6], [3, 6, 0, 9], [3, 6, 3, 6], [3, 6, 3, 9], [3, 6, 12, 6], [3, 6, 12, 9], [3, 9, 0, 6], [3, 9, 0, 9], [3, 9, 3, 6], [3, 9, 3, 9], [3, 9, 12, 6], [3, 9, 12, 9], [12, 6, 0, 6], [12, 6, 0, 9], [12, 6, 3, 6], [12, 6, 3, 9], [12, 6, 12, 6], [12, 6, 12, 9], [12, 9, 0, 6], [12, 9, 0, 9], [12, 9, 3, 6], [12, 9, 3, 9], [12, 9, 12, 6], [12, 9, 12, 9], [1, 7, 1, 7], [1, 7, 1, 10], [1, 7, 4, 7], [1, 7, 4, 10], [1, 7, 13, 7], [1, 7, 13, 10], [1, 10, 1, 7], [1, 10, 1, 10], [1, 10, 4, 7], [1, 10, 4, 10], [1, 10, 13, 7], [1, 10, 13, 10], [4, 7, 1, 7], [4, 7, 1, 10], [4, 7, 4, 7], [4, 7, 4, 10], [4, 7, 13, 7], [4, 7, 13, 10], [4, 10, 1, 7], [4, 10, 1, 10], [4, 10, 4, 7], [4, 10, 4, 10], [4, 10, 13, 7], [4, 10, 13, 10], [13, 7, 1, 7], [13, 7, 1, 10], [13, 7, 4, 7], [13, 7, 4, 10], [13, 7, 13, 7], [13, 7, 13, 10], [13, 10,

\begin{align}
	V_2 =& \{ (v_1 , v_2) \in \mathbb{N}[0,N_y \cdot(m-1)-1] ^2|v_r = l_r \cdot (m-1)+j-1,\ \text{for every}\ r\in\{1,2\}\}
\end{align}

In [5]:
l2j1 = []
for l1 in range(N_y):
	for l2 in range(N_y):
		for j in range(m-1):
			l2j1.append([l1,l2,j+1])
v2 = []
for l2j1_item in l2j1:
	v_1 = l2j1_item[0]*(m-1) + l2j1_item[2] -1
	v_2 = l2j1_item[1]*(m-1) + l2j1_item[2] -1
	v2.append([v_1,v_2])
print(v2)

[[0, 0], [1, 1], [0, 2], [1, 3], [0, 4], [1, 5], [2, 0], [3, 1], [2, 2], [3, 3], [2, 4], [3, 5], [4, 0], [5, 1], [4, 2], [5, 3], [4, 4], [5, 5]]


\begin{align}
	H = \{(u_1,u_2,v)  \in  \mathbb{N}[0,nm-2]^2 \times \mathbb{N}[0,N_y \cdot (m-1)-1]
	|& u_r = (i_r-1)m+j-1,\nonumber\\&v=l\cdot (m-1)+j-1 \nonumber\\& \text{for every}\ r \in \{1,2\}, \ (i_1,i_2)\in C^-  \}
\end{align}

In [6]:
h = []
for j in range (m-1):
	for l in range (N_y):
		for minus_item in minus_set:
			u_1=(minus_item[0]-1)*m + (j+1) -1
			u_2=(minus_item[1]-1)*m + (j+1) -1
			v = l*(m-1) + (j+1) -1
			h.append([u_1,u_2,v])
print(h)

[[0, 6, 0], [0, 9, 0], [3, 6, 0], [3, 9, 0], [12, 6, 0], [12, 9, 0], [0, 6, 2], [0, 9, 2], [3, 6, 2], [3, 9, 2], [12, 6, 2], [12, 9, 2], [0, 6, 4], [0, 9, 4], [3, 6, 4], [3, 9, 4], [12, 6, 4], [12, 9, 4], [1, 7, 1], [1, 10, 1], [4, 7, 1], [4, 10, 1], [13, 7, 1], [13, 10, 1], [1, 7, 3], [1, 10, 3], [4, 7, 3], [4, 10, 3], [13, 7, 3], [13, 10, 3], [1, 7, 5], [1, 10, 5], [4, 7, 5], [4, 10, 5], [13, 7, 5], [13, 10, 5]]


\begin{align}
	l(v) = \left \lfloor v/(m-1) \right\rfloor
\end{align}

In [7]:
def l_func(v):
	return math.floor(v/(m-1))

\begin{gather}
	\sum_{ (u_1,u_2) \in U_2}
	\bigg[
	\lambda_1y_{t(u_1, u_2)} \cdot (1-x_{u_1})+\lambda_2 y_{t(u_1, u_2)} \cdot (1-x_{u_2+1})
	\bigg]
\end{gather}

In [8]:
for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ t + offset1 ,  t + offset1 ] += lambda1

for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ t + offset1 , u2_item[0] ] += -lambda1*0.5
	Q[ u2_item[0], t + offset1  ] += -lambda1*0.5

for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ t + offset1 ,  t + offset1 ] += lambda2

for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ t + offset1 , u2_item[1]+1 ] += -lambda2*0.5
	Q[ u2_item[1]+1, t + offset1  ] += -lambda2*0.5

\begin{gather*}
	\lambda_3 \sum_{ (u_1,u_2) \in U_2}
	\bigg[
	1-x_{u_1}-x_{u_2 +1}+3y_{t(u_1, u_2)}-s_{0t(u_1, u_2)} + 2 x_{u_1} x_{u_2 +1}- 2x_{u_1} y_{t(u_1, u_2)}
	\bigg]
\end{gather*}

In [9]:
for u2_item in u2:
	c += lambda3
for u2_item in u2:
	Q[ u2_item[0], u2_item[0] ] += -lambda3
	Q[ u2_item[1]+1, u2_item[1]+1 ] += -lambda3
for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ t +offset1 , t +offset1  ] += +lambda3*3
for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ t +offset2 , t +offset2  ] += -lambda3
for u2_item in u2:
	if u2_item[0] == u2_item[1]+1:
		Q[ u2_item[0], u2_item[1]+1 ] += lambda3*2
	else:
		Q[ u2_item[0], u2_item[1]+1 ] += lambda3*2*0.5
		Q[ u2_item[1]+1, u2_item[0] ] += lambda3*2*0.5
for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ u2_item[0], t + offset1 ] -= lambda3*2*0.5
	Q[ t + offset1 , u2_item[0] ] -= lambda3*2*0.5

\begin{gather*}
	\lambda_3\sum_{ (u_1,u_2) \in U_2}
	\bigg[+ 2 x_{u_1} s_{0 t(u_1, u_2)}
	+4  x_{u_1}  s_{1 t(u_1, u_2)}
	-2 x_{u_2 +1}y_{t(u_1, u_2)}+2x_{u_2 +1} s_{0t(u_1, u_2)}
	\bigg]
\end{gather*}

In [10]:
for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ u2_item[0], t+offset2 ]  += lambda3*2*0.5
	Q[ t+offset2 , u2_item[0] ] += lambda3*2*0.5
for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ u2_item[0], t+offset3 ] += lambda3*4*0.5
	Q[ t+offset3 , u2_item[0] ] += lambda3*4*0.5
for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[u2_item[1]+1, t+offset1] += -lambda3*2*0.5
	Q[t+offset1,u2_item[1]+1]  += -lambda3*2*0.5
for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[u2_item[1]+1, t+offset2] += lambda3*2*0.5
	Q[ t+offset2,u2_item[1]+1] += lambda3*2*0.5

\begin{gather*}
	\lambda_3\sum_{ (u_1,u_2) \in U_2}
	\bigg[4 x_{u_2 +1}s_{1t(u_1, u_2)}-2 y_{t(u_1, u_2)} s_{0t(u_1, u_2)}-4y_{t(u_1, u_2)}s_{1t(u_1, u_2)}+
	4s_{0t(u_1, u_2)}s_{1t(u_1, u_2)}
	\bigg]
\end{gather*}

In [11]:
for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ u2_item[1]+1, t+offset3 ] += lambda3*4*0.5
	Q[ t+offset3 , u2_item[1]+1 ] += lambda3*4*0.5
for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ t+offset1 , t+offset2 ] += -lambda3*2*0.5
	Q[ t+offset2 , t+offset1 ] += -lambda3*2*0.5
for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ t+offset1 , t+offset3 ] += -lambda3*4*0.5
	Q[ t+offset3 , t+offset1 ] += -lambda3*4*0.5
for u2_item in u2:
	t = u2.index([u2_item[0],u2_item[1]])
	Q[ t+offset2 , t+offset3 ] += lambda3*4*0.5
	Q[ t+offset3 , t+offset2 ] += lambda3*4*0.5

\begin{gather*}
	\sum_{(u_1,u_2,u_3,u_4)  \in U_4} \lambda_4 y_{t(u_2,u_1)} y_{t(u_4,u_3)}
	+\sum_{(u_1,u_2,u_3,u_4)  \in U_4} \lambda_4 y_{t(u_1,u_2)} y_{t(u_3,u_4)}
	+\sum_{(v_1,v_2) \in V_2} 2^{l(v_1)+l(v_2)}\lambda_4 s_{yv_1}s_{y v_2}
\end{gather*}

In [12]:
for u4_item in u4:
	u_1 = u4_item[0]; u_2 = u4_item[1]
	u_3 = u4_item[2]; u_4 = u4_item[3]
	t21 = u2.index([u_2,u_1])
	t43 = u2.index([u_4,u_3])
	if t21 == t43:
		Q[ t21+offset1 , t43+offset1 ] += lambda4
	else:
		Q[ t21+offset1 , t43+offset1 ] += lambda4*0.5
		Q[ t43+offset1 , t21+offset1 ] += lambda4*0.5
for u4_item in u4:
	u_1 = u4_item[0]; u_2 = u4_item[1]
	u_3 = u4_item[2]; u_4 = u4_item[3]
	t12 = u2.index([u_1,u_2])
	t34 = u2.index([u_3,u_4])
	if t12 == t34:
		Q[ t12+offset1 , t34+offset1 ] += lambda4
	else:
		Q[ t12+offset1 , t34+offset1 ] += lambda4*0.5
		Q[ t34+offset1 , t12+offset1 ] += lambda4*0.5
for v2_item in v2:
	v2_1 = v2_item[0]; v2_2 = v2_item[1]
	if v2_1 == v2_2:
		Q[ v2_1+offset4 , v2_2+offset4 ] += math.pow(2,l_func(v2_1)+l_func(v2_2))*lambda4
	else:
		Q[ v2_1+offset4 , v2_2+offset4 ] += math.pow(2,l_func(v2_1)+l_func(v2_2))*lambda4*0.5
		Q[ v2_2+offset4 , v2_1+offset4 ] += math.pow(2,l_func(v2_1)+l_func(v2_2))*lambda4*0.5

\begin{gather*}
	\sum_{(u_1,u_2,u_3,u_4)  \in U_4} (-2)\lambda_4 y_{t(u_2,u_1)} y_{t(u_3,u_4)}
	+\sum_{(u_1,u_2,v) \in H }2^{l(v)+1}\lambda_4 y_{t(u_2,u_1)}s_{y v}
	+\sum_{(u_1,u_2,v) \in H }(-1) 2^{l(v)+1} \lambda_4y_{t(u_1,u_2)}s_{y v}
\end{gather*}

In [13]:
for u4_item in u4:
	u_1 = u4_item[0]; u_2 = u4_item[1]
	u_3 = u4_item[2]; u_4 = u4_item[3]
	t21 = u2.index([u_2,u_1])
	t34 = u2.index([u_3,u_4])
	if t21 == t34:
		Q[  t21+offset1 , t34+offset1 ] += lambda4*(-2)
	else:
		Q[  t21+offset1 , t34+offset1 ] += lambda4*(-2)*0.5
		Q[  t34+offset1 , t21+offset1 ] += lambda4*(-2)*0.5

for h_item in h:
	u_1 = h_item[0]
	u_2 = h_item[1]
	v = h_item[2]
	voff = v + offset4
	t21 = u2.index([u_2,u_1])
	t21off = t21 + offset1
	Q[ t21off , voff ] += math.pow(2,l_func(v)+1)*lambda4*0.5
	Q[ voff , t21off ] += math.pow(2,l_func(v)+1)*lambda4*0.5

for h_item in h:
	u_1 = h_item[0]
	u_2 = h_item[1]
	v = h_item[2]
	voff = v + offset4
	t12 = u2.index([u_2,u_1])
	t12off = t12 + offset1
	Q[ t12off , voff ] += -math.pow(2,l_func(v)+1)*lambda4*0.5
	Q[ voff , t12off ] += -math.pow(2,l_func(v)+1)*lambda4*0.5

In [14]:
print(Q)

[[-20.   0.   0. ...   0.   0.   0.]
 [  0. -40.   0. ...   0.   0.   0.]
 [  0.   0. -20. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... 200.   0. 400.]
 [  0.   0.   0. ...   0. 800.   0.]
 [  0.   0.   0. ... 400.   0. 800.]]


In [15]:
QQ = np.zeros([n*m,n*m])
cc=0
# penalty: "one counterpart per class"
for ii in range(n):
    for jj in range(m):
        tt = ii*m+jj
        QQ[tt][tt] += -1
    for jj in range(m-1):
        for kk in range(jj+1,m):
            tt = ii*m+jj
            rr = ii*m+kk
            QQ[tt][rr] += 1
            QQ[rr][tt] += 1
    cc += 1
# penalty: "first counterpart in first class"
for jj in range(1, m):
    QQ[jj][jj] += 1
    QQ[0][jj] -= 0.5
    QQ[jj][0] -= 0.5

# penalty: "last counterpart in the last class"
for jj in range(m-1):
    tt = (n-1)*m+jj
    QQ[tt][tt] += 1
    QQ[(n*m)-1][tt] -= 0.5
    QQ[tt][(n*m)-1] -= 0.5

# penalty: "penalize not permitted submatrix"
# a submatrix is
# [[x1, x1], [x3, x4]]
for ii in range(n-1):
    for jj in range(m-1):
        x1 = ii*m+jj
        x2 = x1+1
        x3 = (ii+1)*m+jj
        x4 = x3+1
        # add linear terms
        QQ[x1][x1] += 1
        QQ[x4][x4] += 1
        # add quadratic terms
        QQ[x1][x2] += 0.5
        QQ[x2][x1] += 0.5
        QQ[x1][x3] -= 0.5
        QQ[x3][x1] -= 0.5
        QQ[x1][x4] -= 1
        QQ[x4][x1] -= 1
        QQ[x2][x3] += 0.5
        QQ[x3][x2] += 0.5
        QQ[x2][x4] -= 0.5
        QQ[x4][x2] -= 0.5
        QQ[x3][x4] += 0.5
        QQ[x4][x3] += 0.5

# penalty: "penalize restarting from class 0"
# for ii in range(n-1):
#     x1 = ii*m
#     x2 = x1+1
#     x3 = (ii+1)*m
#     QQ[x3][x3] += 1
#     QQ[x1][x3] -= 0.5
#     QQ[x3][x1] -= 0.5
#     QQ[x2][x3] -= 0.5
#     QQ[x3][x2] -= 0.5
#     QQ[x1][x2] += 0.5
#     QQ[x2][x1] += 0.5

In [16]:
print(QQ)

[[ 0.   1.   0.5 -0.5 -1.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0. ]
 [ 1.   1.   1.5  0.5 -1.  -1.   0.   0.   0.   0.   0.   0.   0.   0.
   0. ]
 [ 0.5  1.5  0.   0.   0.5 -0.5  0.   0.   0.   0.   0.   0.   0.   0.
   0. ]
 [-0.5  0.5  0.   0.   2.   1.  -0.5 -1.   0.   0.   0.   0.   0.   0.
   0. ]
 [-1.  -1.   0.5  2.   1.   2.   0.5 -1.  -1.   0.   0.   0.   0.   0.
   0. ]
 [ 0.  -1.  -0.5  1.   2.   0.   0.   0.5 -0.5  0.   0.   0.   0.   0.
   0. ]
 [ 0.   0.   0.  -0.5  0.5  0.   0.   2.   1.  -0.5 -1.   0.   0.   0.
   0. ]
 [ 0.   0.   0.  -1.  -1.   0.5  2.   1.   2.   0.5 -1.  -1.   0.   0.
   0. ]
 [ 0.   0.   0.   0.  -1.  -0.5  1.   2.   0.   0.   0.5 -0.5  0.   0.
   0. ]
 [ 0.   0.   0.   0.   0.   0.  -0.5  0.5  0.   0.   2.   1.  -0.5 -1.
   0. ]
 [ 0.   0.   0.   0.   0.   0.  -1.  -1.   0.5  2.   1.   2.   0.5 -1.
  -1. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -1.  -0.5  1.   2.   0.   0.   0.5
  -0.5]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.5

In [17]:
import gurobipy as gp
from gurobipy import GRB

c=c+cc*lambda5
QQ = QQ*lambda5
QQ=np.pad(QQ, ((0, dim_qubo-n*m), (0, dim_qubo-n*m)), mode='constant', constant_values=0)
Q = QQ+Q
#dim_qubo=n*m


# Create a new model
mm = gp.Model("qubo_solver")

# Create binary variables
x = mm.addVars(dim_qubo, vtype=GRB.BINARY, name="x")

# Set the objective function: minimize x' * Q * x + c
obj = gp.quicksum(Q[i][j] * x[i] * x[j] for i in range(dim_qubo) for j in range(dim_qubo)) + c
mm.setObjective(obj, GRB.MINIMIZE)

# Solve the model
mm.optimize()

# Print the solution
if mm.status == GRB.OPTIMAL:
    print("Optimal solution found.")
    solution = [int(v.X) for v in x.values()]
    print(f"Optimal variable values (x): {solution}")
    print(f"Optimal objective value: {mm.ObjVal}")
else:
    print("No optimal solution found.")

Set parameter Username
Set parameter LicenseID to value 2685653
Gurobi Optimizer version 12.0.3 build v12.0.3rc0 (linux64 - "Ubuntu 24.04.3 LTS")

CPU model: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads

Optimize a model with 0 rows, 93 columns and 0 nonzeros
Model fingerprint: 0x1c6f96be
Model has 482 quadratic objective terms
Variable types: 0 continuous, 93 integer (93 binary)
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  QObjective range [2e+01, 2e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [0e+00, 0e+00]
Found heuristic solution: objective 740.0000000
Found heuristic solution: objective 50.0000000
Found heuristic solution: objective 40.0000000
Found heuristic solution: objective 30.0000000
Presolve removed 0 rows and 6 columns
Presolve time: 0.00s
Presolved: 407 rows, 494 columns, 1221 nonzeros
Variable 

In [18]:
print("number of counterparts: ",n)
print("number of classes: ",m)
print("vector of default values: ",d_vec)
print("num of default: ",d)
print("dimension of the problem: ", dim_qubo)
l=solution[:n*m]
ll=np.array(l)
print(ll.reshape(n,m))
print("lambda coefficients:")
print(lambda1, lambda2, lambda3, lambda4,lambda5, sep=', ')

number of counterparts:  5
number of classes:  3
vector of default values:  [0, 0, 1, 1, 0]
num of default:  2
dimension of the problem:  93
[[1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]]
lambda coefficients:
10, 10, 10, 50, 100
